#!/bin/bash -l
#SBATCH -p debug # change this option for non-debug runs
#SBATCH -t 00:20:00
#SBATCH -A mp309
#SBATCH -o auto-openmp-try24.%j.stdout
#SBATCH -e auto-openmp-try24.%j.error
#SBATCH -N 1

rm openmp-try.txt
srun -n 1 -c 1 ./serial-try -n 500 -no -s openmp-try.txt
export OMP_NUM_THREADS=1
srun -n 1 -c 1 ./openmp-try -p 1 -n 500 -no -s openmp-try.txt
export OMP_NUM_THREADS=2
srun -n 1 -c 2 ./openmp-try -p 2 -n 500 -no -s openmp-try.txt
export OMP_NUM_THREADS=4
srun -n 1 -c 4 ./openmp-try -p 4 -n 500 -no -s openmp-try.txt
export OMP_NUM_THREADS=6
srun -n 1 -c 6 ./openmp-try -p 6 -n 500 -no -s openmp-try.txt
export OMP_NUM_THREADS=12
srun -n 1 -c 12 ./openmp-try -p 12 -n 500 -no -s openmp-try.txt
export OMP_NUM_THREADS=18
srun -n 1 -c 18 ./openmp-try -p 18 -n 500 -no -s openmp-try.txt
export OMP_NUM_THREADS=24
srun -n 1 -c 24 ./openmp-try -p 24 -n 500 -no -s openmp-try.txt
export OMP_NUM_THREADS=2
srun -n 1 -c 2 ./openmp-try -p 2 -n 1000 -no -s openmp-try.txt
export OMP_NUM_THREADS=4
srun -n 1 -c 4 ./openmp-try -p 4 -n 2000 -no -s openmp-try.txt
export OMP_NUM_THREADS=6
srun -n 1 -c 6 ./openmp-try -p 6 -n 3000 -no -s openmp-try.txt
export OMP_NUM_THREADS=12
srun -n 1 -c 12 ./openmp-try -p 12 -n 6000 -no -s openmp-try.txt
export OMP_NUM_THREADS=18
srun -n 1 -c 18 ./openmp-try -p 18 -n 9000 -no -s openmp-try.txt
export OMP_NUM_THREADS=24
srun -n 1 -c 24 ./openmp-try -p 24 -n 12000 -no -s openmp-try.txt
./autograder -v openmp-try -s openmp-try.txt
