#!/bin/bash -l
#SBATCH -p debug # change this option for non-debug runs
#SBATCH -t 00:20:00
#SBATCH -A mp309
#SBATCH -o auto-serial.%j.stdout
#SBATCH -e auto-serial.%j.error
#SBATCH -N 1

rm serial.txt
srun -n 1 -c 1 ./serial_new -n 500 -no -s serial.txt
srun -n 1 -c 1 ./serial_new -n 1000 -no -s serial.txt
srun -n 1 -c 1 ./serial_new -n 2000 -no -s serial.txt
srun -n 1 -c 1 ./serial_new -n 4000 -no -s serial.txt
srun -n 1 -c 1 ./serial_new -n 8000 -no -s serial.txt
srun -n 1 -c 1 ./serial_new -n 16000 -no -s serial.txt
srun -n 1 -c 1 ./serial_new -n 24000 -no -s serial.txt

./autograder -v serial_new -s serial.txt
