#!/bin/bash -l
#SBATCH -p debug # change this option for non-debug runs
#SBATCH -t 00:05:00
#SBATCH -N 24
#SBATCH -A mp309
#SBATCH -o auto-mpi_new24.%j.stdout
#SBATCH -e auto-mpi_new24.%j.error

rm mpi_new.txt
srun -n 1 -N 1 ./serial-try -n 500 -no -s mpi_new.txt
srun -n 1 -N 1 ./mpi_new -p 1 -n 500 -no -s mpi_new.txt
srun -n 2 -N 2 ./mpi_new -p 2 -n 500 -no -s mpi_new.txt
srun -n 4 -N 4 ./mpi_new -p 4 -n 500 -no -s mpi_new.txt
srun -n 6 -N 6 ./mpi_new -p 6 -n 500 -no -s mpi_new.txt
srun -n 12 -N 12 ./mpi_new -p 12 -n 500 -no -s mpi_new.txt
srun -n 18 -N 18 ./mpi_new -p 18 -n 500 -no -s mpi_new.txt
srun -n 24 -N 24 ./mpi_new -p 24 -n 500 -no -s mpi_new.txt
srun -n 2 -N 2 ./mpi_new -p 2 -n 1000 -no -s mpi_new.txt
srun -n 4 -N 4 ./mpi_new -p 4 -n 2000 -no -s mpi_new.txt
srun -n 6 -N 6 ./mpi_new -p 6 -n 3000 -no -s mpi_new.txt
srun -n 12 -N 12 ./mpi_new -p 12 -n 6000 -no -s mpi_new.txt
srun -n 18 -N 18 ./mpi_new -p 18 -n 9000 -no -s mpi_new.txt
srun -n 24 -N 24 ./mpi_new -p 24 -n 12000 -no -s mpi_new.txt
./autograder -v mpi_new -s mpi_new.txt
