#!/bin/bash -l
#SBATCH -p debug # change this option for non-debug runs
#SBATCH -t 00:20:00
#SBATCH -A mp309
#SBATCH -o auto-serial.%j.stdout
#SBATCH -e auto-serial.%j.error
#SBATCH -N 1

rm serial.txt
srun -n 1 -c 1 ./serial-try -n 500 -no -s serial.txt
srun -n 1 -c 1 ./serial-try -n 1000 -no -s serial.txt
srun -n 1 -c 1 ./serial-try -n 2000 -no -s serial.txt
srun -n 1 -c 1 ./serial-try -n 4000 -no -s serial.txt
srun -n 1 -c 1 ./serial-try -n 8000 -no -s serial.txt
./autograder -v serial-try -s serial.txt
