#!/bin/bash -l
#SBATCH -p debug # change this option for non-debug runs
#SBATCH -t 00:10:00
#SBATCH -A mp309
#SBATCH -o serial.%j.stdout
#SBATCH -e serial.%j.error
#SBATCH -N 1

srun -n 1 -c 1 ./serial -n 500 -o serial.txt