#!/bin/bash -l
#SBATCH -p debug # change this option for non-debug runs
#SBATCH -t 00:10:00
#SBATCH -A mp309
#SBATCH -o pthreads24.%j.stdout
#SBATCH -e pthreads24.%j.error
#SBATCH -N 1

srun -n 1 -c 24 ./pthreads -p 24 -n 500 -o pthreads.txt